---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[chef-server::default]
    attributes:

  - name: full
    run_list:
      - recipe[chef-server::server]
      - recipe[chef-server::manage]
    attributes:
